const CONFIG = {
    GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
    GOOGLE_PROJECT_ID: process.env.REACT_APP_GOOGLE_PROJECT_ID,
    GOOGLE_AUTH_URI: process.env.REACT_APP_GOOGLE_AUTH_URI,
    GOOGLE_TOKEN_URI: process.env.REACT_APP_GOOGLE_TOKEN_URI,
    GOOGLE_AUTH_PROVIDER_X509_CERT_URL: process.env.REACT_APP_GOOGLE_AUTH_PROVIDER_X509_CERT_URL,
    GOOGLE_CLIENT_SECRET: process.env.REACT_APP_GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URIS: process.env.REACT_APP_GOOGLE_REDIRECT_URIS.split(',')
};

export default CONFIG;
